# Generated by Django 5.1.2 on 2024-10-24 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_acontuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='acontuser',
            name='cargo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='position_account', to='accounts.position'),
        ),
        migrations.AddField(
            model_name='acontuser',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unit_account', to='accounts.unit'),
        ),
    ]
