# Generated by Django 5.1.2 on 2024-11-01 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_acontuser_cargo_acontuser_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='acontuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile/', verbose_name='Foto'),
        ),
    ]
