# Generated by Django 5.1.2 on 2024-11-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_acontuser_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='logradouro',
            field=models.CharField(blank=True, choices=[('Rua', 'Rua'), ('AV', 'Avenida'), ('ES', 'Estrada')], max_length=50, null=True),
        ),
    ]
