# Generated by Django 5.1.2 on 2024-11-29 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_unit_logradouro'),
    ]

    operations = [
        migrations.AddField(
            model_name='acontuser',
            name='path',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Caminho Arquivos'),
        ),
    ]
