# Generated by Django 5.1.2 on 2024-12-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_acontuser_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='acontuser',
            name='saldo',
            field=models.IntegerField(default=0),
        ),
    ]
