# Generated by Django 5.1.2 on 2024-12-27 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_acontuser_saldo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acontuser',
            name='saldo',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
