# Generated by Django 5.1.2 on 2024-12-27 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0008_alter_acontuser_saldo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ferias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_vacation', models.DateField(unique=True, verbose_name='Data inicio:')),
                ('end_vacation', models.DateField(verbose_name='Data Fim')),
                ('month', models.CharField(blank=True, default='', max_length=25)),
                ('year', models.CharField(blank=True, default='', max_length=25)),
                ('pessoa_vacation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ferias_pessoa', to=settings.AUTH_USER_MODEL, verbose_name='Colaborador')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ferias_unidade', to='accounts.unit', verbose_name='Unidade')),
            ],
        ),
        migrations.CreateModel(
            name='Folga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('motivo', models.CharField(choices=[('DOMINGO TRABALHADO', 'TRABALHADO'), ('COMBINADO GESTOR', 'COMBINADO'), ('OUTROS', 'OUTROS')], max_length=25)),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('date_updated', models.DateField(blank=True, null=True)),
                ('status_folga', models.CharField(choices=[('PENDENTE', 'PENDENTE'), ('APROVADO', 'APROVADO'), ('RECUSADO', 'RECUSADO')], default='PENDENTE', max_length=25)),
                ('observacao', models.TextField(blank=True, max_length=50, null=True, verbose_name='Observação:')),
                ('folga_pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folga_pessoa', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='folga_unidade', to='accounts.unit')),
            ],
        ),
    ]
